default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost

development:
  <<: *default
  database: books_development

test:
  <<: *default
  database: books_test

production:
  <<: *default
  database: books_production
  username: postgres
  password: root
